### ISSUE TITLE
Sign in not working

### ISSUE THREAD

**Issue by javnino** [NewmanCatalysis/ITProCloudEssentials#6]
![sign in not able to complete](https://cloud.githubusercontent.com/assets/18334781/14362012/7671b63e-fcb2-11e5-8e41-18d238272c13.jpg)

log in at 10:30 am PST - 4/7/2016
Edge/Safari/Chrome
Seattle area

**Comment by NewmanCatalysis** [comment]
Closing.  This is a Microsoft server issue.
