### ISSUE TITLE
MVP not able to redeem the voucher

### ISSUE THREAD

**Issue by javnino** [NewmanCatalysis/ITProCloudEssentials#7]
<img width="721" alt="techrewards not working" src="https://cloud.githubusercontent.com/assets/18334781/14368357/1384ca50-fcd2-11e5-82da-978d468fb5ba.png">

4/7/2016
3:05 pm PST
Florida, US

**Comment by NewmanCatalysis** [comment]
Reached out to Stephanie Yang via email just now.

**Comment by NewmanCatalysis** [comment]
Confirmed working.  Server on Voucher side was down for updates.
